### ISSUE TITLE
Create How To Test doc 

### ISSUE THREAD

**Issue by critesjosh** [AztecProtocol/dev-rel#111]
We have this [testing page](https://docs.aztec.network/dev_docs/tutorials/writing_dapp/testing) in the "Writing a DApp" tutorial, [this testing page](https://docs.aztec.network/dev_docs/tutorials/testing) as a standalone tutorial and the ["Testing" top level section](https://docs.aztec.network/dev_docs/testing/main).

We should combine these.

**Comment by critesjosh** [comment]
Testing should probably be a how-to rather than a tutorial

**Comment by critesjosh** [comment]
@catmcgee all of the pages I originally linked have moved. Do you think this issue is still relevant or should we close it?

**Comment by catmcgee** [comment]
@critesjosh still think this is a good thing to have so moving back to Planned

**Comment by critesjosh** [comment]
Since this back in Planned, do you have an estimate of when you will have capacity to work on this? I created more Iterations, so we can schedule issues for future weeks.

**Comment by catmcgee** [comment]
@critesjosh added iteration 37, could probably pick it up in 36. thanks for adding more iterations :)
