### ISSUE TITLE
Review state of Aztec Boxes

### ISSUE THREAD

**Issue by critesjosh** [AztecProtocol/dev-rel#134]
Try all of the aztec boxes (blank, blank-react, and token).

- [ ] Update READMEs
- [ ] Evaluate what would be required to get refactor, simplify and add UI tests. 
- [ ] Share findings here

**Comment by signorecello** [comment]
Tracking progress [here](https://github.com/AztecProtocol/aztec-packages/pull/4183)

**Comment by signorecello** [comment]
So here's my conclusion:

## Blank Box ✅

This one is already barebones enough for us. It could easily replace `aztec-starter` and adding an `npx` functionality should be straightforward. This is a quick win IMO.

## Blank React Box ✅

The React one has cool things that do fit a starter kit very well such as helper functions to interact with a PXE. Plus, it is a React starter and we can expect most devs to choose it if they want to bootstrap a React app.

But it can be stripped down by a lot. Plus, the tests only cover Jest tests so if the frontend is broken, we will never know. So here are the proposed changes:

- Strip it to the bones. We believe things like form validation, event listeners, "copy to clipboard" links, etc, these are cool but don't fit a starter kit. The dev is expected to possess the knowledge to add custom frontend stuff themselves.
- Add a frontend test, this could be something like playwright, cypress, whatever

## Token Box 😕

It's an amazing example and really a powerful e2e thing. But it's definitely not a boilerplate in any way. I would make it an example, perhaps spinning it off to an "examples" kind of box?

It does some very good e2e testing, which may or may not be a bit redundant with other tests in the repo?

In any case, I wouldn't consider Token Box as a starter.
