### ISSUE TITLE
SPIKE next steps

### ISSUE THREAD

**Issue by signorecello** [AztecProtocol/dev-rel#147]

**Comment by signorecello** [comment]
So, here's where we're at:

# Blank box

This one looks fine. I think it can easily make its way into a starter.

# Blank-React

As mentioned in #134 this could use some stripping down, as it is quite opinionated on a bunch of features we would like the dev to be able to implement themselves. Here's the task list:

- [ ] Remove konami code easter egg (lol)
- [ ] Remove irrelevant terms and conditions page
- [ ] Remove copy to clipboard buttons and stuff
- [ ] Flatten every action into one page (no modals , no dropdown for selecting wallet, showing available actions, etc). One page is enough with the bare essential
- [ ] Remove warning popups. Use alerts or toasters if something needs to succeed/fail
- [ ] Turn function call handles into hooks
- [ ] Refactor the contract to have one contract call and one view function. Make one button say "VIEW FUNCTION" that alerts a view value, and "CALL FUNCTION" with an input. Remove form validation.
- [ ] Remove most of the styling

I believe in 1 day one should be able to make these changes and have a barebones react box

**Comment by critesjosh** [comment]
Follow up to this, did you get a chance to look into how much work it would be to add a UI testing framework?

**Comment by signorecello** [comment]
It's hard to know because I would have to learn how to use playwright so I'm gonna say a wrong figure 💯  maybe it could be worth refactoring this and then make a decision based on pessimistic estimates? I mean I never spent more than 2-3 days learning the basics of any new framework so I could say maybe EOW...

**Comment by signorecello** [comment]
IMO refactoring this to have two actual starters is already a win, and a fairly quick one at that. Adding a frontend test is just a good contrib to the codebase and would give us some peace of mind

**Comment by critesjosh** [comment]
Agree. The front-end testing shouldn't be a blocker for this.

**Comment by signorecello** [comment]
Closing this for now
