### ISSUE TITLE
improve diagrams on docs page

### ISSUE THREAD

**Issue by critesjosh** [AztecProtocol/dev-rel#152]
[this](https://docs.aztec.network/concepts/foundation/communication/cross_chain_calls)  page

**Comment by critesjosh** [comment]
submitting a design request for these.

![Image](https://github.com/AztecProtocol/dev-rel/assets/18372439/c7ea15ee-703a-4748-83b9-11a20af20c41)

**Comment by Demian101** [comment]
COOL!

**Comment by critesjosh** [comment]
design request submitted

**Comment by critesjosh** [comment]
PR https://github.com/AztecProtocol/aztec-packages/pull/4368
