### ISSUE TITLE
Discuss: autogenerated sidebar in Aztec docs?

### ISSUE THREAD

**Issue by critesjosh** [AztecProtocol/dev-rel#166]

**Comment by critesjosh** [comment]
@signorecello @catmcgee Can i move this back to the backlog since iirc we agreed to table this for a bit?

**Comment by jzaki** [comment]
May use doc tags.

**Comment by critesjosh** [comment]
I think this was discussed at the commercial offsite. can we close?

**Comment by signorecello** [comment]
Yep let's close it. For the record, the answer is YES
