### ISSUE TITLE
Codespaces for boxes

### ISSUE THREAD

**Issue by signorecello** [AztecProtocol/dev-rel#179]
This is actually part of the boxes work, since the idea is to replace aztec-starter there has to be feature parity

**Comment by critesjosh** [comment]
Some feedback from the eng offsite, there is no mention of codespaces in the docs. Are you planning to add boxes info as a docs page? if so, we should mention codespaces, once we have it

**Comment by signorecello** [comment]
Closed with with #aztec-packages/5849
