### ISSUE TITLE
Crowdfunding app tutorial in docs (from the eng offsite)

### ISSUE THREAD

**Issue by critesjosh** [AztecProtocol/dev-rel#187]
slack thread: https://aztecprotocol.slack.com/archives/C049J23DN64/p1709555358390289

**Comment by jzaki** [comment]
Related [4917](https://github.com/AztecProtocol/aztec-packages/pull/4917)

Aztec-packages-v0.26.5
- [Claim_contract](https://github.com/AztecProtocol/aztec-packages/tree/aztec-packages-v0.26.5/noir-projects/noir-contracts/contracts/claim_contract)
- [crowdfunding_contract](https://github.com/AztecProtocol/aztec-packages/tree/aztec-packages-v0.26.5/noir-projects/noir-contracts/contracts/crowdfunding_contract)

**Comment by critesjosh** [comment]
@jzaki this is closed by this PR https://github.com/AztecProtocol/aztec-packages/pull/5786, correct?
