### ISSUE TITLE
Reference doc of all Aztec macros

### ISSUE THREAD

**Issue by jzaki** [AztecProtocol/dev-rel#189]
User Story - As a developer new to Aztec, I would like an understanding of what goes on in macros (eg "private"), so that I can have confidence in writing privacy preserving applications.

There are some references to different macros around the docs, but a search doesn't yield a doc that readily lists them all, defining what they do.

Task - Create a reference doc that generally explains Aztec macros, and defines each one.

**Comment by jzaki** [comment]
Summary of function level macros can be seen in VSCode via `Ctrl+K` then `Ctrl+2` (fold to depth 2), then `Ctrl+K` then `Ctrl+J` (to unfold)

Related https://github.com/AztecProtocol/aztec-packages/issues/5162

**Comment by critesjosh** [comment]
Related: https://github.com/AztecProtocol/dev-rel/issues/200 <- this one is an explainer vs a reference
