### ISSUE TITLE
Boxes / codespaces doc page

### ISSUE THREAD

**Issue by critesjosh** [AztecProtocol/dev-rel#192]
this could be completed by https://github.com/AztecProtocol/dev-rel/issues/185, but could also be a separate page

**Comment by signorecello** [comment]
Thinking it can be a separate page. Here's my suggestion:
- Replace all references to aztec-starter in the docs by the codespaces method
- Create 2-3 badges people can click and immediately get to the "create codespaces" page with everything filled in (I read Github purposefully does not allow links that create codespaces immediatelly)
- Tweet about this
