### ISSUE TITLE
Noir recursion example

### ISSUE THREAD

**Issue by critesjosh** [AztecProtocol/dev-rel#197]

**Comment by critesjosh** [comment]
@catmcgee what's the status of this? There are questions coming up in discord where this might be helpful. cc @signorecello

**Comment by signorecello** [comment]
At least trying 2 in 1 proof verifications because that's what's unclear if it's working or not

We can flesh out the "real-world use-case" later on

**Comment by signorecello** [comment]
Assigning to @jzaki since @catmcgee will be busy with alpha hack

**Comment by jzaki** [comment]
Recurse summation (simple example like chaining hashes up a tree), use `backend_binary` directly to avoid mem limit in bb wasm
