### ISSUE TITLE
Docs: explainer about macros

### ISSUE THREAD

**Issue by jzaki** [AztecProtocol/dev-rel#200]
blocked until new docs structure

**Comment by jzaki** [comment]
Related slack thread
1. From what I can see the name `_initialize` doesn't have special meaning, and is just convention (like in bb and wasm) ?
2. The contract is [checked](https://github.com/AztecProtocol/aztec-packages/blob/master/noir/noir-repo/aztec_macros/src/lib.rs#L105) for having a macro defining `initializer`, if so, then every function will default to disallowing calls before the/an initializer function has been called?
  - `noinitcheck` overrides this check and will call it without needing the/a preceding `initializer` function being called?
  - Multiple functions can be defined as `initializer`, and any one will allow other functions to be called (that don't have noinitcheck)?
3. `internal` simply does what it says on the tin [here](https://github.com/AztecProtocol/aztec-packages/blob/master/noir/noir-repo/aztec_macros/src/transforms/functions.rs#L39)?

and [doc](https://docs.aztec.network/developers/contracts/writing_contracts/functions/initializers)

**Comment by critesjosh** [comment]
Do we need to wait until there is a new docs structure to work on this?

**Comment by catmcgee** [comment]
> Do we need to wait until there is a new docs structure to work on this?

No, especially because docs structure won't be started on for another 3 weeks. i'll take this as i'm assigned

**Comment by catmcgee** [comment]
add Grego as a reviewer
