### ISSUE TITLE
Docs: Structure refactor

### ISSUE THREAD

**Issue by critesjosh** [AztecProtocol/dev-rel#221]
Consider removing the "Learn" section altogether (or maybe big parts of it). Since the protocol specs have been published, those pages should be considered the source of truth for the associated information. (e.g. reviewing the info on Trees, there are some discrepencies)

**Comment by critesjosh** [comment]
@signorecello from what i understand, this is going to be started after the DEX alpha build wraps up, correct?

**Comment by critesjosh** [comment]
As part of the refactor, keep in mind the developer learning journey, related to https://github.com/AztecProtocol/dev-rel/issues/142

Maybe we end up creating a new page that guides a new reader through the documentation

**Comment by signorecello** [comment]
This is mostly being done in AztecProtocol/aztec-packages#6195.

Some things to improve for a stacked PR, or for creating an issue for later:

[] - Improve frontmatter, most pages don't even have it and it's crucial for SEO
[] - Move guides out of reference, further separate tutorials from guides and etc
[] - Remove stuff, remove remove remove
