### ISSUE TITLE
Brainstorm tutorial app ideas

### ISSUE THREAD

**Issue by catmcgee** [AztecProtocol/dev-rel#227]

**Comment by critesjosh** [comment]
Brainstorm call scheduled for monday April 29th

**Comment by critesjosh** [comment]
Priorities / projects we want to build

- Face/TouchID (IAM)
- NFT demo contract (v similar to token) + prove ownership for token sale (KYC -> NFT?) (IAM + gaming)
- Battleships or Blackjack (gaming)

Notes:
https://docs.google.com/document/d/1lwCZPV0Eg3n4Sk6E3vGAsP7q29f608DUXoOdTmO1_ow/edit
