### ISSUE TITLE
Design Face/TouchID app

### ISSUE THREAD

**Issue by catmcgee** [AztecProtocol/dev-rel#229]
- Face/TouchID (IAM)
- NFT demo contract (v similar to token) + prove ownership for token sale (KYC -> NFT?) (IAM + gaming)

**Comment by catmcgee** [comment]
blocked until https://github.com/AztecProtocol/dev-rel/issues/227

**Comment by critesjosh** [comment]
For faceID, could be as simple as using an existing account contract implementation and replacing ECDSA signature verification with faceID verification

**Comment by critesjosh** [comment]
@jzaki did you find the noir library for the webauthn curve?
