### ISSUE TITLE
Design and write NFT contract + token gating

### ISSUE THREAD

**Issue by catmcgee** [AztecProtocol/dev-rel#230]
- NFT demo contract (v similar to token) + prove ownership for token gating
- small tutorial for NFT
- big tutorial / reference for token gating

**Comment by catmcgee** [comment]
blocked by https://github.com/AztecProtocol/dev-rel/issues/227

**Comment by critesjosh** [comment]
related #233

**Comment by catmcgee** [comment]
this will change with key stuff (token contract changing) but want to do it anyway

**Comment by catmcgee** [comment]
You need to get the note contents and derive a note hash (remember notes have npk_m_hash in them!)
You need prove note hash in the note hash tree and not in nullifier tree.
But you also need to show the note is in the balances map of the nft contract. Luckily note contents have the storage slot which do this!
Prove that the note is assosciated to your address - luckily, like 3, nothing extra to do. Note is stored in a map, whose storage slot is derived based the address) which brings me to:
zk proof that you actually own the address (your private key owns the address). Get them to sign a message and verify the sig (what is_valid_impl does on account contracts)

**Comment by catmcgee** [comment]
blocking for now. makes more sense to do this when eng has done more exploration into primitivs we need
