### ISSUE TITLE
Docs: authwit how to with both aztecnr and ts

### ISSUE THREAD

**Issue by catmcgee** [AztecProtocol/dev-rel#247]

**Comment by critesjosh** [comment]
Adding some info about public authwits from a relevant discord discussion

```ts
const action = asset.withWallet(wallets[1]).methods.transfer_public(accounts[0].address, accounts[1].address, amount, nonce);

await wallets[0].setPublicAuthWit({ caller: accounts[1].address, action }, true).send().wait();
```

`asset` - the token you are authorizing spending of
`wallets[1]` - the wallet that will be sending the transaction to the network
`accounts[0].address` - the address that the tokens are coming from
`accounts[1].address` - the address that you are sending the tokens to
`caller` - the address that will be making the call, this will be the uniswap contract address in your case i believe 

from [this test](https://github.com/AztecProtocol/aztec-packages/blob/0fa509b68da7a8ab1b5865d17a7cf4cb197eb8b3/yarn-project/end-to-end/src/e2e_token_contract/transfer_public.test.ts#L51)
