### ISSUE TITLE
Check EVM chains for Noir Solidity verifier compatibility

### ISSUE THREAD

**Issue by critesjosh** [AztecProtocol/dev-rel#255]
Mark each with ✅ or ❌ 

1. Tron
2. BSC
3. Arbitrum
4. Blast
5. Base
6. Merlin
7. Avalanche
8. Polygon
9. Optimism
10. Cronos

related to: https://github.com/noir-lang/noir/issues/4964

**Comment by critesjosh** [comment]
The quickest way to test might be to get the default Solidity verifier, paste it into remix, deploy to a corresponding testnet and try to verify a proof

**Comment by Savio-Sou** [comment]
On further research, it's probably best to exclude Tron as it is not nor is it aiming to be Ethereum EVM compatible: https://developers.tron.network/docs/tvm#differences-from-evm

As of now then the [top 10 EVMs by TVL](https://defillama.com/chains/EVM) list becomes:
1. BSC
2. Arbitrum
3. Blast
4. Base
5. Merlin
6. Polygon (PoS)
7. Avalanche
8. Optimism
9. Linea
10. Mode

**Comment by signorecello** [comment]
So we're tackling:
- BSC
- Blast
- Merlin
- Linea
- Mode

I would recommend using volume instead of TVL, although on DefiLlama it only gives us 24h volume. In any case seems like the resulting list would probably be more in line with what people are using

**Comment by Savio-Sou** [comment]
24h volume sounds easily fluctuating due to e.g. campaigns, short-term sentiments, etc.

If we have a reliable data source of for example 30d volume, that could be a good metric to switch over for; otherwise starting with TVL seems simplest.
