### ISSUE TITLE
Docs: account abstraction in Aztec.nr

### ISSUE THREAD

**Issue by catmcgee** [AztecProtocol/dev-rel#264]
Account abstraction (showing "constructor abstraction", nonce abstraction, fee abstraction-ish with paymasters)

**Comment by critesjosh** [comment]
I added info on fee and nonce abstraction in this PR (https://github.com/AztecProtocol/aztec-packages/pull/6345)  here https://github.com/AztecProtocol/aztec-packages/pull/6345/commits/d35c9f118a4fb4302513813f42eeda15e45aa7b7

**Comment by critesjosh** [comment]
Closing because the commit in my comment was merged.
