### ISSUE TITLE
Update references to Notes to use nullifier keys

### ISSUE THREAD

**Issue by critesjosh** [AztecProtocol/dev-rel#279]
Do to keys and key rotation being updated, Notes now use the `nullifier_key`  instead of an `address` to indicate ownership of a note. 

Things to update:
- [ ] any Note references
- [ ] adding the pattern to `common_patterns.md` -- devs need to remember that these keys can be rotated!
- [ ] include an explanation / example code for how to handle key rotation

slack reference: https://aztecprotocol.slack.com/archives/C049J23DN64/p1715261619302879

**Comment by jzaki** [comment]
Related https://github.com/AztecProtocol/aztec-packages/pull/6387
