### ISSUE TITLE
Update `how-to-oracles`

### ISSUE THREAD

**Issue by Savio-Sou** [AztecProtocol/dev-rel#282]
```[tasklist]
### Prerequisite
- [ ] https://github.com/noir-lang/noir/pull/5072
```

Following https://github.com/noir-lang/noir/pull/5072, proving and verification workflow would no longer rely on NoirJS but proving backends' JS packages (e.g. bb.js) instead.

That in turn requires updating the instructions of how JS packages are used in the https://noir-lang.org/docs/how_to/how-to-oracles doc page.

As the `how-to-oracles` example in this repo is linked and used as the basis of that doc page, we would have to update it as a part of updating the doc page.

**Comment by critesjosh** [comment]
I don't see a reference to proving or verifying on that page. maybe we can close this?

**Comment by Savio-Sou** [comment]
Hey @critesjosh, let's treat this as a code audit and close as completed if things are tested working on latest Noir / Issues are created if it's not working. How does that sound?
