### ISSUE TITLE
[docs] Noir performance considerations

### ISSUE THREAD

**Issue by critesjosh** [AztecProtocol/dev-rel#300]
From tom on slack:

- Try to avoid mutating arrays at unknown (until runtime) indices as this turns ROM into RAM which is more expensive. In this case it's best to construct the final output in an unconstrained function and then assert that it's correct.
- Unconstrained gud, so also useful in non-array settings if you can prove the result cheaply once you know it.
- Bitwise operations are bad and should be avoided if possible (notable as devs tend to use bitwise ops in an attempt to optimise their code)
- We do as much compile-time execution as we can so calling "expensive" functions with constant arguments isn't a major concern and developers shouldn't feel the need to create hardcoded constants.

**Comment by jzaki** [comment]
This ticket is about bringing general insights for developing Noir into the Noir docs. The draft hackmd consolidates and communicates key points from several Aztec devs.
