### ISSUE TITLE
Hidden macros explainer

### ISSUE THREAD

**Issue by catmcgee** [AztecProtocol/dev-rel#309]
Could we also include an explaiantion for hidden "macros" (things we inject within a user's noir contract without them having to explicitly write a macro). One example that you all are aware of is adding compute_note_hash_and_nullifier() . There are several of these.

another one - the way we generate a contract interface by default now to make calls to a function within the contract much nicer

**Comment by catmcgee** [comment]
https://github.com/AztecProtocol/aztec-packages/pull/7784

**Comment by critesjosh** [comment]
@catmcgee can we merge the associated PR now?

**Comment by catmcgee** [comment]
will close today
