### ISSUE TITLE
[docs]: docs audit

### ISSUE THREAD

**Issue by critesjosh** [AztecProtocol/dev-rel#317]
Do a general skim of each page of the docs, figuring out which pages need to be updated. Create an issue for pages / sections that need to be updated. Add them to this (https://github.com/AztecProtocol/dev-rel/issues/220) issue and assign a priority

**Comment by catmcgee** [comment]
update sandbox commands

**Comment by critesjosh** [comment]
@catmcgee is this closed via [this](https://github.com/AztecProtocol/aztec-packages/pull/7640), or do you want to keep it open?
