### ISSUE TITLE
New design for docs and developer portal

### ISSUE THREAD

**Issue by catmcgee** [AztecProtocol/dev-rel#338]

**Comment by catmcgee** [comment]
- Including general elevation improvements
    - How to use tags
    - How can we improve search
    - Separating some of the eng-written docs into their type (there are often mixes of explanations & howtos)
- Put a design request through for developer portal

**Comment by catmcgee** [comment]
i sent this over to design
https://docs.google.com/document/d/1tdoU_AA3T_ic_t7bCSbJZ6McLle0Ex7Q-6mOE1vjKpE/edit

This is for docs

## Structure

### Top level

- Concepts
    - The things currently in aztec
- Guides
    - Includes getting-started
- Examples
    - These are our tutorials
- Reference
- Resources
    - GitHub
        - aztec-packages
        - awesome-aztec
    - Other docs
        - Noir docs
        - Protocol spec
    - Support
        - Discord
        - Newsletter

## Tags

- Every page should have a tag with at least one concept
    - Accounts
    - Notes
    - PXE
    - TXE
    - Contracts (private/public state/functions)
    - Circuits (as much as a dev should know)
    - Portals
    - Fees
    - Privacy
    - CLI
    - LSP
    - Testing
- Show tags on page that people can click on ✔️

## Colours

Change colours to match Aztec colours

- Background:
- Headers:
- Bullets:
- Links:
- Tips:
- Warnings:

## Search

- filter search results by tag and category
- use AI to figure out what they want
- only explore the top level menu they are currently on
- implement tracking
    - can implement specific queries
- add synonyms
- highlight parts of the tect that are relevent
- autocomplete

**Comment by catmcgee** [comment]
I marked sept 1st as deadline for design

**Comment by critesjosh** [comment]
I see this is marked as done, can we close? 

 you close the issue, it will automatically update to "Done"
