### ISSUE TITLE
Redo Learn/Concepts section and figure out what diagrams we need

### ISSUE THREAD

**Issue by catmcgee** [AztecProtocol/dev-rel#346]

**Comment by catmcgee** [comment]
put in design request for diagrams
animations even cooler!

**Comment by critesjosh** [comment]
There are a bunch of diagrams that have not been added to the appropriate docs pages yet, here: https://drive.google.com/drive/folders/1SAEcPWtafhoNvKiJkcIfnboagqZMO90a

**Comment by catmcgee** [comment]
make overview page more about intuitions, why, how
https://docs.aztec.network/aztec/overview
