### ISSUE TITLE
Authwit code reference fix

### ISSUE THREAD

**Issue by catmcgee** [AztecProtocol/dev-rel#354]
mike: I was just brushing up on authwits, and this code snippet in this section seems to have been modified so that it no-longer demonstrates any authwit functionality, meaning the text below the code snippet is out of date. Perhaps the name of the docs:start:<name> wasn't descriptive enough to hint to the engineer that their code changes might break commentary on authwits. https://docs.aztec.network/guides/smart_contracts/writing_contracts/authwit#checking-if-the-current-call-is-authenticated

**Comment by critesjosh** [comment]
closed by https://github.com/AztecProtocol/aztec-packages/pull/7640
