### ISSUE TITLE
[docs]: CLI wallet docs

### ISSUE THREAD

**Issue by catmcgee** [AztecProtocol/dev-rel#362]
Explainig all the intricacies and fun stuff (some wallet info in this [PR](https://github.com/AztecProtocol/aztec-packages/pull/7725) description)

**Comment by critesjosh** [comment]
more details [here](https://github.com/AztecProtocol/aztec-packages/pull/7856#event-13821734948)

**Comment by critesjosh** [comment]
@signorecello closing this, feel free to reopen if needed.
