### ISSUE TITLE
[docs]: add some partial notes docs

### ISSUE THREAD

**Issue by catmcgee** [AztecProtocol/dev-rel#382]
One request/modification - can we make the use cases section more tailored for external devs. Instead of a hyper specific example like FPC (which isn't relevant for most), lets use an app example:
DEX: Currently to swap privately, there are 2 tx: one to start your swap from ETH->DAI. And later to privately claim DAI from the DEX. Instead you can create a partial swaped note (create a DAI note with nil value). And in public complete it with the final amount!
Lending: same as DEX. Borrow privately and claim the borrowed token in 1 tx instead of 2!
Shielding: going from public -> private. We won't use partial notes for this case but still a good example to build mental models.
Refunds: original inspiration for partial notes. Currently you need 2 transactions: to initiate a refund. And another to claim refund note. We can combine to 1 step. In the example of fees on Aztec: without partial notes, you have to claim your refund note. But the act of claiming itself needs gas! What if you overpaid fees on the refund tx? Then you have another 2nd order refund that you need to claim. This creates a never ending cycle!

**Comment by critesjosh** [comment]
> Shielding: going from public -> private. We won't use partial notes for this case but still a good example to build mental models.

Not sure if we should mention this if it's not going to be used. I feel like it could introduce confusion
