### ISSUE TITLE
[docs]: Update custom note docs

### ISSUE THREAD

**Issue by critesjosh** [AztecProtocol/dev-rel#385]
feedback from a community member. These are some questions they had that they could not find answers to.

explain what does `#[aztec(note)]` do. Explain each field. Why do we need `randomness`, why do we need `npk_m_hash`, what does `serialize_content`, explain `context.request_nsk_app`, explain `get_nsk_app(self.npk_m_hash)`. What if there is no `npk_m_hash`(in case of a multisig, i believe)? Why is `trait Eq` is implemented manually instead of `#[derive(Eq)]`?

**Comment by catmcgee** [comment]
small changes for now but this + general notes docs will be fixed in this issue https://github.com/AztecProtocol/dev-rel/issues/346
