### ISSUE TITLE
Review metaprogramming macros docs

### ISSUE THREAD

**Issue by jzaki** [AztecProtocol/dev-rel#405]

**Comment by critesjosh** [comment]
This has been documented, just need to review the page in the docs, per Savio's request

**Comment by jzaki** [comment]
- Side bar subheadings are broken
- Useful to link to [std lib](https://noir-lang.org/docs/dev/noir/standard_library/meta/)
- Would benefit from more examples (split into [this issue](https://github.com/noir-lang/noir-examples/issues/26))
