### ISSUE TITLE
Update noir-starter to use noir js

### ISSUE THREAD

**Issue by signorecello** [AztecProtocol/dev-rel#54]
https://github.com/noir-lang/noir-starter/issues/51

**Comment by signorecello** [comment]
Blocking because of this:
https://zpedro.notion.site/Noir-js-Devex-Notes-0e5aea3b3caf49ed942cc37b37242a72?pvs=4

**Comment by Savio-Sou** [comment]
Thanks for putting the doc together!

Just to confirm, is:

> Noir.js is ESM-only. We’re currently supporting both, so this blocks further attempts to integrate it with noir-starter or any of the other examples.

the only blocking issue on the Notion list?

And it's blocking since noir-starter uses hardhat which is CommonJS-based?
