### ISSUE TITLE
Docs: docs philosophy

### ISSUE THREAD

**Issue by signorecello** [AztecProtocol/dev-rel#72]
draft an internal doc / deck about what our theory around docs is, how to introduce concepts, build on them and demonstrate with complex examples, so it can be used as a reference going forward. once we have that we can reference it in the call and show what we mean with examples (of our docs, or others that we think are good) and people can look at it in the future

**Comment by critesjosh** [comment]
Should this be marked as ongoing? Is there ongoing work associated with this?
