### ISSUE TITLE
Aztec docs: Replicate Noir monorepo workflow

### ISSUE THREAD

**Issue by signorecello** [AztecProtocol/dev-rel#84]
Noir docs workflow turned out really cool. We get previews there, which we don't in Aztec monorepo. Let's do that.

- [ ] Replicate Noir workflow in Aztec monorepo
- [ ] Spike the idea of making a custom workflow that lives in the devrel repository

**Comment by signorecello** [comment]
Low prio because we can live without previews (can build locally).

Estimating small because workflow should be about the same. Don't intend to go too far with the spike

**Comment by critesjosh** [comment]
What do you mean by "Spike the idea of making a custom workflow that lives in the devrel repository"?

**Comment by critesjosh** [comment]
@signorecello i am going to close this for now as i think the needs for the two docs sites are quite different atm.
