### ISSUE TITLE
Automated testing for dev-rel/tutorials

### ISSUE THREAD

**Issue by critesjosh** [AztecProtocol/dev-rel#93]
Set up github testing, or something similar, to ensure that our tutorials are up to date and notify us when they break.

- need to run sandbox
- run tests

This was a point of friction at ETH london.

**Comment by signorecello** [comment]
Broke this into two:
- #97 for noir-starter
- this one for tutorials (would run on the DevRel repo)

**Comment by critesjosh** [comment]
I think we may be able to get away with not testing the tutorial code if we can find a way to pull the latest contract code and corresponding tests directly from the latest aztec-packages release tag. I believe @catmcgee is working on this

**Comment by signorecello** [comment]
gonna assign @catmcgee , Cat feel free to close if this is covered elsewhere

**Comment by catmcgee** [comment]
https://github.com/AztecProtocol/dev-rel/pull/101

**Comment by critesjosh** [comment]
@catmcgee can i close this?
